version: '3'

services:
  wppconnect:
    container_name: wpp-server
    restart: unless-stopped
    build:
      context: .
    volumes:
      - wppconnect_tokens:/usr/src/wpp-server/tokens
      # Declaramos o arquivo de forma relativa. O Coolify vai ler isso e criar o campo na aba Storages
      - ./src/config.ts:/usr/src/wpp-server/src/config.ts
    ports:
      - '21465:21465'
    expose:
      - '21465'

volumes:
  wppconnect_tokens: {}
